---
- name: check if "{{ swapfile }}" is exist
  stat:
    path: "{{ swapfile }}"
  become: yes
  register: stat_result

- include: swap.yml
  when: stat_result.stat.exists == false

# - name: remove container with name nexus if exists
#   docker_container:
#     name: nexus
#     state: absent
#  ignore_errors: yes

# - name: start container nexus
#  command: "docker run -d -p 8081:8081 --name nexus hbkmustang/nexus3-gw-setup"

- name: start container nexus
  docker_container:
    name: nexus
    image: hbkmustang/nexus3-gw-setup
    state: started
    published_ports:
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
    volumes:
      - nexus-data:/nexus-data
    detach: yes
    auto_remove: yes
  become: yes

- name: Waiting for service
  wait_for:
    port: 8081
    state: started
    host: 0.0.0.0
    timeout: 60
    delay: 5
