---
- name: allocate swap
  command: "{{ item }}"
  become: yes
  loop:
  - "fallocate -l 2G {{ swapfile }}"

- name: "changing permissions and owner for {{ swapfile }}"
  file:
    path: "{{ swapfile }}"
    owner: root
    group: root
    mode: '0600'    
  become: yes

- name: turn on swap in system
  command: "{{ item }}"
  become: yes
  loop:
  # - "chmod 600 "{{ swapfile }}""
  - "mkswap {{ swapfile }}"
  - "swapon {{ swapfile }}"
  
- name: add swap to fstab if it does not exist
  lineinfile:
    path: /etc/fstab
    line: "{{ swapfile }}   swap    swap    sw  0   0"
  become: yes
  # register: result_replace_in_file
