---
- name: Upload public key to AWS
  ec2_key:
    name: "{{ key_file }}"
    key_material: "{{ lookup('file', '{{ key_path }}{{ key_file }}.pub') }}"
    region: "{{ region }}"
    aws_access_key: "{{ec2_access_key}}"
    aws_secret_key: "{{ec2_secret_key}}"
