---
- name: Terminate instance "{{ name_of_instance }}"
  ec2:
    aws_access_key: "{{ec2_access_key}}"
    aws_secret_key: "{{ec2_secret_key}}"
    key_name: "{{ key_file }}"
    instance_ids: "{{ instance_id }}"
    region: "{{ region }}"
    wait: true
    state: absent
  
- name: Delete security group
  ec2_group:
    name: "{{ sec_group }}"
    # description: "Sec group for app {{ instance_name }}"
    # vpc_id: 12345
    region: "{{ region }}"
    aws_access_key: "{{ec2_access_key}}"
    aws_secret_key: "{{ec2_secret_key}}"
    state: absent
  register: result_sec_group        
