---
- name: Start instance "{{ name_of_instance }}"
  ec2:
    aws_access_key: "{{ec2_access_key}}"
    aws_secret_key: "{{ec2_secret_key}}"
    key_name: "{{ key_file }}"
    instance_ids: "{{ instance_id }}"
    region: "{{ region }}"
    wait: true
    state: running
