---
#- debug:
#    msg: "{{ route53_action }}"

- name: "{{ route53_action }} dns record with route53 {{ instance_name }}.{{ workzone }}"
  route53:
    aws_access_key: "{{ec2_access_key}}"
    aws_secret_key: "{{ec2_secret_key}}"
    state: "{{ route53_action }}"
    zone: "{{ workzone }}"
    record: "{{ instance_name }}.{{ workzone }}."
    type: "{{ route53_type }}"
    ttl: "{{ dnsttl }}"
    value: "{{ ip_address }}"
    overwrite: yes
    wait: no

- name: "{{ route53_action }} dns record with route53 {{ instance_name }}-local.{{ workzone }}"
  route53:
    aws_access_key: "{{ec2_access_key}}"
    aws_secret_key: "{{ec2_secret_key}}"
    state: "{{ route53_action }}"
    zone: "{{ workzone }}"
    record: "{{ instance_name }}-local.{{ workzone }}."
    type: "{{ route53_type }}"
    ttl: "{{ dnsttl }}"
    value: "{{ ip_address_private }}"
    overwrite: yes
    wait: no
